import React from 'react'
import {
  Section, Container, Stack, Accordion, CodeBlock, Alert, Badge, Card, Divider,
} from '@agustin/aqus'

// ── code snippets ─────────────────────────────────────────────────────────────

const INSTALL = `npm install github:LagoJournal/Aqus`
const INIT    = `npx aqus init`

const INIT_FLOW = `# What init does, step by step:

  1. Pick an accent color (preset palette or custom H / C / L)
  2. Generate aqus.css — all 9 tokens, light + dark mode
  3. Inject @import into your entry file (auto-detected)
  4. Optionally install the Aqus design agent for Claude Code`

const COMPOSE = `import { NavBar, Section, Container, Button, Card } from '@agustin/aqus'

export function Dashboard() {
  return (
    <>
      <NavBar
        links={[{ href: '#', label: 'Overview' }, { href: '#', label: 'Settings' }]}
        action={<Button variant="primary" size="sm">New project</Button>}
      />
      <Section>
        <Container>
          <Card>Card content here.</Card>
        </Container>
      </Section>
    </>
  )
}`

const AGENT_PROMPT = `# Once the agent is installed, just describe what you want:
# "Build a dashboard with a NavBar, three stat cards, and a line chart."
#
# The agent knows every component, UX rule, and brand guideline.
# It will compose a complete, importable view — no manual token wiring.`

const MANUAL_CSS = `// src/main.jsx (or app/layout.tsx, pages/_app.tsx, etc.)
import '@agustin/aqus/styles.css'
import './aqus.css'   // ← generated by npx aqus init`

const MANUAL_ACCENT = `/* aqus.css — generated by npx aqus init, edit freely */
:root {
  --accent-h:      265;
  --accent:        oklch(0.60 0.21 265);
  --accent-hover:  oklch(0.54 0.23 265);
  --accent-light:  oklch(0.92 0.074 265);
  --accent-mid:    oklch(0.78 0.116 265);
  --accent-text:   oklch(0.25 0.053 265);
  --accent-glow:   oklch(0.60 0.21 265 / 0.25);
  --accent-glass:  oklch(0.60 0.21 265 / 0.12);
  --focus-ring:    oklch(0.60 0.25 265 / 0.80);
  --on-accent:     oklch(0.99 0.005 265);
}

[data-theme="dark"] {
  --accent:        oklch(0.68 0.21 265);
  --accent-hover:  oklch(0.74 0.19 265);
  --accent-light:  oklch(0.30 0.074 265);
  --accent-mid:    oklch(0.42 0.116 265);
  --accent-text:   oklch(0.88 0.053 265);
  --accent-glow:   oklch(0.68 0.21 265 / 0.28);
  --accent-glass:  oklch(0.68 0.21 265 / 0.12);
  --focus-ring:    oklch(0.68 0.25 265 / 0.75);
  --on-accent:     oklch(0.15 0.02  265);
}`

// ── accordion items ───────────────────────────────────────────────────────────

const STEPS = [
  {
    id: 'install',
    title: (
      <Stack direction="row" gap={2} align="center">
        <Badge tone="accent" pill>1</Badge>
        <span>Install the package</span>
      </Stack>
    ),
    content: (
      <Stack gap={3}>
        <p className="sc-item-desc">Pin to a version to lock components, tokens, and docs together.</p>
        <CodeBlock language="bash" code={INSTALL} />
      </Stack>
    ),
  },
  {
    id: 'init',
    title: (
      <Stack direction="row" gap={2} align="center">
        <Badge tone="accent" pill>2</Badge>
        <span>Run init — sets up everything</span>
      </Stack>
    ),
    content: (
      <Stack gap={3}>
        <p className="sc-item-desc">
          One command configures your accent color, writes the CSS, wires up imports,
          and installs the design agent for Claude Code if detected.
        </p>
        <CodeBlock language="bash" code={INIT} />
        <CodeBlock language="bash" code={INIT_FLOW} />
        <Alert tone="accent" title="Agent-first">
          When Claude Code is present, init offers to install the Aqus design agent —
          a trained skill that knows every component, UX rule, and brand guideline.
          Once installed, describe the UI you want and the agent builds it for you.
        </Alert>
      </Stack>
    ),
  },
  {
    id: 'compose',
    title: (
      <Stack direction="row" gap={2} align="center">
        <Badge tone="accent" pill>3</Badge>
        <span>Compose — manually or with the agent</span>
      </Stack>
    ),
    content: (
      <Stack gap={3}>
        <p className="sc-item-desc">
          Import components directly and build screens from primitives.
          Never re-style raw HTML — always use the library components.
        </p>
        <CodeBlock language="tsx" code={COMPOSE} />
        <CodeBlock language="bash" code={AGENT_PROMPT} />
      </Stack>
    ),
  },
]

const MANUAL_STEPS = [
  {
    id: 'manual-css',
    title: <span style={{ fontSize: 'var(--text-body-sm)' }}>Manual CSS import</span>,
    content: (
      <Stack gap={3}>
        <p className="sc-item-desc">Add both imports to your app entry point.</p>
        <CodeBlock language="tsx" code={MANUAL_CSS} />
        <Alert tone="accent" title="Dark mode">
          Set <code>data-theme="dark"</code> on any ancestor element to activate the dark elevation ramp.
        </Alert>
      </Stack>
    ),
  },
  {
    id: 'manual-accent',
    title: <span style={{ fontSize: 'var(--text-body-sm)' }}>Manual accent tokens</span>,
    content: (
      <Stack gap={2}>
        <p className="sc-item-desc">
          All 9 tokens derive from one hue. Constraints: L 0.55–0.72, C 0.12–0.24.
          The chart palette derives from <code>--accent-h</code> automatically.
        </p>
        <CodeBlock language="css" code={MANUAL_ACCENT} />
      </Stack>
    ),
  },
]

// ── component ─────────────────────────────────────────────────────────────────

export function Usage() {
  return (
    <Section id="usage" size="md" className="anchor">
      <Container>
        <p className="sc-eyebrow">Quick start</p>
        <h2 className="sc-section-title">Install, init, build.</h2>
        <p className="sc-section-lede">
          Aqus is designed to be used through its Claude agent — a trained skill that knows
          every component, UX law, brand rule, and voice guideline. One command sets it all up.
        </p>

        {/* Agent capability callout */}
        <Card variant="resting" style={{ padding: 24, marginBottom: 32 }}>
          <Stack gap={3}>
            <Stack direction="row" gap={3} align="center" wrap>
              <div style={{
                width: 44, height: 44, flex: 'none',
                borderRadius: 'var(--radius-md)',
                background: 'var(--accent-glass)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 22, color: 'var(--accent)',
              }}>
                <i className="ph ph-robot" />
              </div>
              <Stack gap={0} style={{ minWidth: 0 }}>
                <span style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 'var(--text-body-lg)', color: 'var(--text)' }}>
                  The Aqus design agent
                </span>
                <span className="sc-item-desc">Trained on every component, UX rule, and brand guideline in this library</span>
              </Stack>
            </Stack>
            <Divider />
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 200px), 1fr))', gap: 16 }}>
              {[
                { icon: 'ph-stack', label: '76 components', desc: 'Knows when to use each one and when not to' },
                { icon: 'ph-scales', label: '10 UX laws', desc: 'Applies Fitts, Hick, Miller, Doherty automatically' },
                { icon: 'ph-paint-brush', label: 'Brand rules', desc: 'Glass only on chrome, liquid = shape not behavior' },
                { icon: 'ph-chat-text', label: 'Voice system', desc: 'Right register, sentence case, no fluff words' },
              ].map(f => (
                <Stack key={f.label} direction="row" gap={2} align="flex-start">
                  <i className={`ph ${f.icon}`} style={{ color: 'var(--accent)', fontSize: 18, marginTop: 1, flex: 'none' }} />
                  <Stack gap={0}>
                    <span style={{ fontSize: 'var(--text-body-sm)', fontWeight: 600, color: 'var(--text)' }}>{f.label}</span>
                    <span className="sc-item-desc">{f.desc}</span>
                  </Stack>
                </Stack>
              ))}
            </div>
          </Stack>
        </Card>

        {/* Main steps */}
        <Accordion items={STEPS} />

        {/* Manual reference */}
        <div style={{ marginTop: 32 }}>
          <p style={{ fontSize: 'var(--text-body-sm)', color: 'var(--text-muted)', marginBottom: 12 }}>
            Manual setup reference — if you prefer to configure without the CLI
          </p>
          <Accordion items={MANUAL_STEPS} />
        </div>
      </Container>
    </Section>
  )
}
