/**
 * Aqus accent token generator.
 * Derives all 9 CSS custom properties + dark variants from H, C, L.
 * Formula defined in src/tokens/ACCENT.md.
 */

export const PRESETS = [
  { name: 'Blue',    H: 245, C: 0.20, L: 0.60 },
  { name: 'Violet',  H: 292, C: 0.21, L: 0.60 },
  { name: 'Cyan',    H: 200, C: 0.18, L: 0.62 },
  { name: 'Teal',    H: 165, C: 0.20, L: 0.60 },
  { name: 'Emerald', H: 145, C: 0.20, L: 0.60 },
  { name: 'Amber',   H:  55, C: 0.22, L: 0.62 },
  { name: 'Orange',  H:  38, C: 0.22, L: 0.62 },
  { name: 'Rose',    H:  15, C: 0.20, L: 0.60 },
  { name: 'Pink',    H: 340, C: 0.20, L: 0.58 },
  { name: 'Purple',  H: 318, C: 0.20, L: 0.58 },
]

/**
 * Hue 245–285 reads as blue, not violet, despite what people expect.
 * Returns a warning string when a hue is in that ambiguous zone, else null.
 * True violet starts ~285; the Violet preset sits at 292 for real separation.
 */
export function hueWarning(H) {
  if (H > 245 && H < 285) {
    return `Hue ${H} reads blue-violet — for a clearly violet accent use ~290+ (see the Violet preset, H 292).`
  }
  return null
}

function r(n) { return Math.round(n * 1000) / 1000 }

function oklch(L, C, H, alpha) {
  const l = r(L), c = r(C), h = r(H)
  return alpha !== undefined
    ? `oklch(${l} ${c} ${h} / ${alpha})`
    : `oklch(${l} ${c} ${h})`
}

export function generateTokens({ H, C, L }) {
  return {
    light: {
      '--accent-h':     String(H),
      '--accent':       oklch(L,        C,        H),
      '--accent-hover': oklch(L - 0.06, C + 0.02, H),
      '--accent-light': oklch(0.92,     C * 0.35, H),
      '--accent-mid':   oklch(0.78,     C * 0.55, H),
      '--accent-text':  oklch(0.25,     C * 0.25, H),
      '--accent-glow':  oklch(L,        C,        H, 0.25),
      '--accent-glass': oklch(L,        C,        H, 0.12),
      '--focus-ring':   oklch(L,        C + 0.04, H, 0.80),
      '--on-accent':    oklch(0.99,     0.005,    H),
    },
    dark: {
      '--accent':       oklch(L + 0.08,  C,        H),
      '--accent-hover': oklch(L + 0.14,  C - 0.02, H),
      '--accent-light': oklch(0.30,      C * 0.35, H),
      '--accent-mid':   oklch(0.42,      C * 0.55, H),
      '--accent-text':  oklch(0.88,      C * 0.25, H),
      '--accent-glow':  oklch(L + 0.08,  C,        H, 0.28),
      '--accent-glass': oklch(L + 0.08,  C,        H, 0.12),
      '--focus-ring':   oklch(L + 0.08,  C + 0.04, H, 0.75),
      '--on-accent':    oklch(0.15,      0.02,     H),
    },
  }
}

export function renderCSS({ H, C, L }) {
  const { light, dark } = generateTokens({ H, C, L })

  const lightBlock = Object.entries(light)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')

  const darkBlock = Object.entries(dark)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')

  return `/* Aqus accent — generated by \`npx aqus init\`
   Edit H (hue 0-360), C (chroma 0.12-0.24), L (lightness 0.55-0.72)
   then re-run init or adjust the values manually. */

:root {
${lightBlock}
}

[data-theme="dark"] {
${darkBlock}
}
`
}
